const SUPABASE_URL = 'COLE_AQUI_A_URL_DO_SUPABASE_PESSOAL';

const SUPABASE_KEY = 'COLE_AQUI_A_CHAVE_PUBLICAVEL_DO_SUPABASE_PESSOAL';

const supabaseClient = supabase.createClient(
  SUPABASE_URL,
  SUPABASE_KEY
);
